language: csharp
solution: net-sdk.sln

deploy:
  provider: script
  skip_cleanup: true
  script:
    - cd net-sdk && nuget pack net-sdk.nuspec -Version 1.0.3 -IncludeReferencedProjects -Prop Configuration=Release && nuget push *.nupkg '68c4ae5d-8365-4d27-9066-ca29a9f0198d' -verbosity detailed
  on:
    branch: second-release
  