language: csharp
solution: net-sdk.sln

install:
  - nuget restore net-sdk.sln
  
script:
  - xbuild /p:DebugSymbols=False /p:Configuration=Release net-sdk.sln /p:TargetFrameworkVersion="v4.5"
  - xbuild net-sdk.sln
  